apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    name: echo-server-deployment
    type: learning
spec:
  replicas: 1
  selector:
    matchLabels:
      name: echo-server-pod

  template:
    metadata:
      labels:
        name: echo-server-pod

    spec:
      containers:
        - name: echo-server
          image: 'robblovell/echo-server:2.2'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
