apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    name: echo-server-service
    role: server
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  selector:
    name: echo-server-pod
